name: Build Geode Mod

on:
  workflow_dispatch:  # Позволяет запустить сборку вручную
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, macos]
        target: [Win64, Android64]  # Платформы для сборки

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
      uses: geode-sdk/build-geode-mod@main
      with:
        combine: true  # Если true, несколько сборок для разных платформ объединятся в один `.geode`-файл
        target: ${{ matrix.target }}
