name: Build Geode Mod

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: Win64
          - os: macos-latest
            target: macOS
          - os: ubuntu-latest
            target: Android64
          - os: ubuntu-latest
            target: Android32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest
          cli: latest
          target: ${{ matrix.target }}
          build-config: Release
          combine: true
